name: Build

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  dry-release:
    name: dry release
    uses: mathieu-keller/github-action-workflows/.github/workflows/semantic-release.yaml@2.0.1
    with:
      release-branch: main
      dry: true
  test:
    name: test
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./src
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.0
    - name: Checkout
      uses: actions/checkout@v4
    - name: install dep
      run: go get -v ./...
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  release:
    name: create release
    needs: [test]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: mathieu-keller/github-action-workflows/.github/workflows/semantic-release.yaml@2.0.1
    with:
      release-branch: main
      dry: false
